#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define ID_DLG_ABOUT                            100
#define ID_ICON_ABOUT                           110
#define ID_LTEXT_ABOUT2                         122
#define ID_LTEXT_ABOUT3                         123
#define ID_LTEXT_ABOUT4                         124
#define ID_DLG_PASSPHRASE                       150
#define ID_EDT_PASSPHRASE                       151
#define ID_LTEXT_PASSWORD                       152
#define ID_PASSWORD_REVEAL                      153
#define ID_DLG_STATUS                           160
#define ID_TXT_STATUS                           161
#define ID_DISCONNECT                           163
#define ID_RESTART                              164
#define ID_HIDE                                 165
#define ID_TXT_VERSION                          166
#define ID_DETACH                               167
#define ID_TXT_BYTECOUNT                        168
#define ID_TXT_IP                               169
#define ID_DLG_CHGPASS                          170
#define ID_EDT_PASS_CUR                         174
#define ID_EDT_PASS_NEW                         175
#define ID_EDT_PASS_NEW2                        176
#define ID_TXT_KEYFILE                          177
#define ID_TXT_KEYFORMAT                        178
#define ID_DLG_AUTH                             180
#define ID_EDT_AUTH_USER                        181
#define ID_EDT_AUTH_PASS                        182
#define ID_DLG_AUTH_CHALLENGE                   183
#define ID_TXT_AUTH_CHALLENGE                   184
#define ID_EDT_AUTH_CHALLENGE                   185
#define ID_CHK_SAVE_PASS                        186
#define ID_TXT_WARNING                          187
#define ID_LTEXT_USERNAME                       188
#define ID_LTEXT_RESPONSE                       189
#define ID_DLG_CHALLENGE_RESPONSE               190
#define ID_TXT_DESCRIPTION                      191
#define ID_EDT_RESPONSE                         192
#define ID_DLG_PROXY                            200
#define ID_GROUPBOX3                            203
#define ID_RB_PROXY_OPENVPN                     210
#define ID_RB_PROXY_MSIE                        211
#define ID_RB_PROXY_MANUAL                      212
#define ID_RB_PROXY_HTTP                        213
#define ID_EDT_PROXY_ADDRESS                    214
#define ID_EDT_PROXY_PORT                       215
#define ID_TXT_PROXY_ADDRESS                    216
#define ID_TXT_PROXY_PORT                       217
#define ID_RB_PROXY_SOCKS                       219
#define ID_DLG_GENERAL                          230
#define ID_CMB_LANGUAGE                         231
#define ID_TXT_LANGUAGE                         232
#define ID_CHK_STARTUP                          233
#define ID_CHK_LOG_APPEND                       236
#define ID_CHK_SILENT                           237
#define ID_TXT_BALLOON                          238
#define ID_RB_BALLOON0                          239
#define ID_RB_BALLOON1                          240
#define ID_RB_BALLOON2                          241
#define ID_CHK_SHOW_SCRIPT_WIN                  242
#define ID_CHK_ALWAYS_USE_ISERVICE              243
#define ID_RB_BALLOON3                          244
#define ID_RB_BALLOON4                          245
#define ID_RB_BALLOON5                          246
#define ID_TXT_PERSISTENT                       247
#define ID_CHK_PLAP_REG                         248
#define ID_CHK_AUTO_RESTART                     249
#define ID_DLG_PROXY_AUTH                       250
#define ID_EDT_PROXY_USER                       251
#define ID_EDT_PROXY_PASS                       252
#define ID_DLG_ADVANCED                         270
#define ID_TXT_FOLDER                           271
#define ID_TXT_EXTENSION                        272
#define ID_EDT_CONFIG_DIR                       274
#define ID_EDT_CONFIG_EXT                       275
#define ID_EDT_LOG_DIR                          276
#define ID_BTN_CONFIG_DIR                       277
#define ID_BTN_LOG_DIR                          278
#define ID_TXT_PRECONNECT_TIMEOUT               279
#define ID_TXT_CONNECT_TIMEOUT                  280
#define ID_TXT_DISCONNECT_TIMEOUT               281
#define ID_EDT_PRECONNECT_TIMEOUT               282
#define ID_EDT_CONNECT_TIMEOUT                  283
#define ID_EDT_DISCONNECT_TIMEOUT               284
#define ID_EDT_MGMT_PORT                        285
#define ID_TXT_FOLDER1                          286
#define ID_EDT_POPUP_MUTE                       287
#define ID_DLG_MESSAGE                          300
#define ID_TXT_MESSAGE                          301
#define ID_DLG_URL_PROFILE_IMPORT               400
#define ID_EDT_URL                              401
#define ID_CHK_AUTOLOGIN                        402
#define ID_DLG_PKCS11_QUERY                     450
#define ID_LVW_PKCS11                           451
#define ID_TXT_PKCS11                           452
#define ID_CHK_CONCAT_OTP                       470
#define IDS_LANGUAGE_NAME                       40000
#define IDS_TIP_CONNECTED                       40001
#define IDS_TIP_CONNECTING                      40002
#define IDS_TIP_CONNECTED_SINCE                 40003
#define IDS_TIP_ASSIGNED_IP                     40004
#define IDS_MENU_SERVICE                        40005
#define IDS_MENU_IMPORT                         40006
#define IDS_MENU_IMPORT_AS                      40007
#define IDS_MENU_IMPORT_URL                     40008
#define IDS_MENU_IMPORT_FILE                    40009
#define IDS_MENU_SETTINGS                       40010
#define IDS_MENU_CLOSE                          40011
#define IDS_MENU_CONNECT                        40012
#define IDS_MENU_DISCONNECT                     40013
#define IDS_MENU_RECONNECT                      40014
#define IDS_MENU_STATUS                         40015
#define IDS_MENU_VIEWLOG                        40016
#define IDS_MENU_EDITCONFIG                     40017
#define IDS_MENU_PASSPHRASE                     40018
#define IDS_MENU_CLEARPASS                      40019
#define IDS_MENU_SERVICE_START                  40020
#define IDS_MENU_SERVICE_STOP                   40021
#define IDS_MENU_SERVICE_RESTART                40022
#define IDS_MENU_SERVICEONLY_START              40023
#define IDS_MENU_SERVICEONLY_STOP               40024
#define IDS_MENU_SERVICEONLY_RESTART            40025
#define IDS_MENU_ASK_STOP_SERVICE               40026
#define IDS_ERR_START_LOG_VIEWER                40027
#define IDS_ERR_START_CONF_EDITOR               40028
#define IDS_ERR_MANY_CONFIGS                    40029
#define IDS_NFO_NO_CONFIGS                      40030
#define IDS_ERR_CONFIG_NOT_AUTHORIZED           40031
#define IDS_ERR_CONFIG_TRY_AUTHORIZE            40032
#define IDS_NFO_CONFIG_AUTH_PENDING             40033
#define IDS_ERR_ADD_USER_TO_ADMIN_GROUP         40034
#define IDS_ERR_ONE_CONN_OLD_VER                40035
#define IDS_ERR_STOP_SERV_OLD_VER               40036
#define IDS_ERR_CREATE_EVENT                    40037
#define IDS_ERR_UNKNOWN_PRIORITY                40038
#define IDS_ERR_LOG_APPEND_BOOL                 40039
#define IDS_ERR_GET_MSIE_PROXY                  40040
#define IDS_ERR_INIT_SEC_DESC                   40041
#define IDS_ERR_SET_SEC_DESC_ACL                40042
#define IDS_ERR_CREATE_PIPE_OUTPUT              40043
#define IDS_ERR_CREATE_PIPE_INPUT               40044
#define IDS_ERR_DUP_HANDLE_OUT_READ             40045
#define IDS_ERR_DUP_HANDLE_IN_WRITE             40046
#define IDS_ERR_CREATE_PROCESS                  40047
#define IDS_ERR_CREATE_THREAD_STATUS            40048
#define IDS_NFO_STATE_WAIT_TERM                 40049
#define IDS_NFO_STATE_CONNECTED                 40050
#define IDS_NFO_STATE_ONHOLD                    40051
#define IDS_NFO_NOW_CONNECTED                   40052
#define IDS_NFO_ASSIGN_IP                       40053
#define IDS_ERR_CERT_EXPIRED                    40054
#define IDS_ERR_CERT_NOT_YET_VALID              40055
#define IDS_NFO_STATE_RECONNECTING              40056
#define IDS_NFO_STATE_DISCONNECTED              40057
#define IDS_NFO_CONN_TERMINATED                 40058
#define IDS_NFO_STATE_FAILED                    40059
#define IDS_NFO_CONN_FAILED                     40060
#define IDS_NFO_STATE_FAILED_RECONN             40061
#define IDS_NFO_RECONN_FAILED                   40062
#define IDS_NFO_STATE_SUSPENDED                 40063
#define IDS_ERR_READ_STDOUT_PIPE                40064
#define IDS_ERR_CREATE_EDIT_LOGWINDOW           40065
#define IDS_ERR_SET_SIZE                        40066
#define IDS_ERR_AUTOSTART_CONF                  40067
#define IDS_ERR_CREATE_PIPE_IN_READ             40068
#define IDS_NFO_STATE_CONNECTING                40069
#define IDS_NFO_CONNECTION_XXX                  40070
#define IDS_NFO_STATE_CONN_SCRIPT               40071
#define IDS_NFO_STATE_DISCONN_SCRIPT            40072
#define IDS_ERR_RUN_CONN_SCRIPT                 40073
#define IDS_ERR_GET_EXIT_CODE                   40074
#define IDS_ERR_CONN_SCRIPT_FAILED              40075
#define IDS_ERR_RUN_CONN_SCRIPT_TIMEOUT         40076
#define IDS_ERR_CONFIG_EXIST                    40077
#define IDS_NFO_CONN_TIMEOUT                    40078
#define IDS_ERR_OPEN_DEBUG_FILE                 40079
#define IDS_ERR_CREATE_PATH                     40080
#define IDS_ERR_LOAD_RICHED20                   40081
#define IDS_ERR_SHELL_DLL_VERSION               40082
#define IDS_NFO_SERVICE_STARTED                 40083
#define IDS_NFO_SERVICE_STOPPED                 40084
#define IDS_NFO_ACTIVE_CONN_EXIT                40085
#define IDS_ERR_PARSE_MGMT_OPTION               40086
#define IDS_NFO_SERVICE_ACTIVE_EXIT             40087
#define IDS_NFO_STATE_ROUTE_ERROR               40088
#define IDS_NFO_USAGE                           40088
#define IDS_NFO_NOTIFY_ROUTE_ERROR              40089
#define IDS_NFO_USAGECAPTION                    40089
#define IDS_ERR_BAD_PARAMETER                   40090
#define IDS_ERR_BAD_OPTION                      40091
#define IDS_ERR_CREATE_PASS_THREAD              40092
#define IDS_NFO_CHANGE_PWD                      40093
#define IDS_ERR_PWD_DONT_MATCH                  40094
#define IDS_ERR_PWD_TO_SHORT                    40095
#define IDS_NFO_EMPTY_PWD                       40096
#define IDS_ERR_UNKNOWN_KEYFILE_FORMAT          40097
#define IDS_ERR_OPEN_PRIVATE_KEY_FILE           40098
#define IDS_ERR_OLD_PWD_INCORRECT               40099
#define IDS_ERR_OPEN_WRITE_KEY                  40100
#define IDS_ERR_WRITE_NEW_KEY                   40101
#define IDS_NFO_PWD_CHANGED                     40102
#define IDS_ERR_READ_PKCS12                     40103
#define IDS_ERR_CREATE_PKCS12                   40104
#define IDS_ERR_OPEN_CONFIG                     40105
#define IDS_ERR_ONLY_ONE_KEY_OPTION             40106
#define IDS_ERR_ONLY_KEY_OR_PKCS12              40107
#define IDS_ERR_ONLY_ONE_PKCS12_OPTION          40108
#define IDS_ERR_HAVE_KEY_OR_PKCS12              40109
#define IDS_ERR_KEY_FILENAME_TO_LONG            40110
#define IDS_ERR_PASSPHRASE2STDIN                40111
#define IDS_ERR_AUTH_USERNAME2STDIN             40112
#define IDS_ERR_AUTH_PASSWORD2STDIN             40113
#define IDS_ERR_CR2STDIN                        40114
#define IDS_ERR_INVALID_CHARS_IN_PSW            40115
#define IDS_SETTINGS_CAPTION                    40116
#define IDS_ERR_HTTP_PROXY_ADDRESS              40117
#define IDS_ERR_HTTP_PROXY_PORT                 40118
#define IDS_ERR_HTTP_PROXY_PORT_RANGE           40119
#define IDS_ERR_SOCKS_PROXY_ADDRESS             40120
#define IDS_ERR_SOCKS_PROXY_PORT                40121
#define IDS_ERR_SOCKS_PROXY_PORT_RANGE          40122
#define IDS_ERR_CREATE_REG_HKCU_KEY             40123
#define IDS_ERR_GET_TEMP_PATH                   40124
#define IDS_ERR_OPEN_VPN_SERVICE                40125
#define IDS_ERR_START_SERVICE                   40126
#define IDS_ERR_QUERY_SERVICE                   40127
#define IDS_ERR_SERVICE_START_FAILED            40128
#define IDS_ERR_OPEN_SCMGR                      40129
#define IDS_ERR_STOP_SERVICE                    40130
#define IDS_NFO_RESTARTED                       40131
#define IDS_ERR_ACCESS_SERVICE_PIPE             40132
#define IDS_ERR_WRITE_SERVICE_PIPE              40133
#define IDS_ERR_INSTALL_ISERVICE                40134
#define IDS_ERR_NOTSTARTED_ISERVICE             40135
#define IDS_ERR_NOTSTARTED_ISERVICE_ADM         40136
#define IDS_ERR_GET_WINDOWS_DIR                 40137
#define IDS_ERR_GET_PROFILE_DIR                 40138
#define IDS_ERR_GET_PROGRAM_DIR                 40139
#define IDS_ERR_OPEN_REGISTRY                   40140
#define IDS_ERR_READING_REGISTRY                40141
#define IDS_ERR_PASSPHRASE_ATTEMPTS             40142
#define IDS_ERR_CONN_SCRIPT_TIMEOUT             40143
#define IDS_ERR_DISCONN_SCRIPT_TIMEOUT          40144
#define IDS_ERR_PRECONN_SCRIPT_TIMEOUT          40145
#define IDS_ERR_CREATE_REG_KEY                  40146
#define IDS_ERR_OPEN_WRITE_REG                  40147
#define IDS_ERR_READ_SET_KEY                    40148
#define IDS_ERR_WRITE_REGVALUE                  40149
#define IDS_ERR_PLAP_REG                        40150
#define IDS_ERR_PLAP_UNREG                      40151
#define IDS_ERR_IMPORT_EXISTS                   40152
#define IDS_ERR_IMPORT_FAILED                   40153
#define IDS_NFO_IMPORT_SUCCESS                  40154
#define IDS_NFO_IMPORT_OVERWRITE                40155
#define IDS_NFO_IMPORT_SOURCE                   40156
#define IDS_ERR_IMPORT_SOURCE                   40157
#define IDS_ERR_IMPORT_ACCESS                   40158
#define IDS_NFO_DELETE_PASS                     40159
#define IDS_NFO_TOKEN_PASSWORD_CAPTION          40160
#define IDS_NFO_TOKEN_PASSWORD_REQUEST          40161
#define IDS_NFO_AUTH_PASS_RETRY                 40162
#define IDS_NFO_KEY_PASS_RETRY                  40163
#define IDS_ERR_INVALID_PASSWORD_INPUT          40164
#define IDS_ERR_INVALID_USERNAME_INPUT          40165
#define IDS_NFO_AUTO_CONNECT                    40166
#define IDS_NFO_CLICK_HERE_TO_START             40167
#define IDS_NFO_BYTECOUNT                       40168
#define IDS_NFO_OTP_PROMPT                      40169
#define IDS_ERR_URL_IMPORT_PROFILE              40170
#define IDS_ERR_NO_PKCS11                       40171
#define IDS_ERR_SELECT_PKCS11                   40172
#define IDS_CERT_DISPLAYNAME                    40173
#define IDS_CERT_ISSUER                         40174
#define IDS_CERT_NOTAFTER                       40175
#define IDS_NFO_STATE_RETRYING                  40176
#define IDS_NFO_STATE_CANCELLING                40177
#define IDS_NFO_STATE_DISCONNECTING             40178
#define IDS_NFO_CONN_CANCELLED                  40179
#define IDS_NFO_OVPN_STATE_INITIAL              40180
#define IDS_NFO_OVPN_STATE_CONNECTING           40181
#define IDS_NFO_OVPN_STATE_ASSIGN_IP            40182
#define IDS_NFO_OVPN_STATE_ADD_ROUTES           40183
#define IDS_NFO_OVPN_STATE_CONNECTED            40184
#define IDS_NFO_OVPN_STATE_RECONNECTING         40185
#define IDS_NFO_OVPN_STATE_EXITING              40186
#define IDS_NFO_OVPN_STATE_WAIT                 40187
#define IDS_NFO_OVPN_STATE_AUTH                 40188
#define IDS_NFO_OVPN_STATE_GET_CONFIG           40189
#define IDS_NFO_OVPN_STATE_RESOLVE              40190
#define IDS_NFO_OVPN_STATE_TCP_CONNECT          40191
#define IDS_NFO_OVPN_STATE_AUTH_PENDING         40192
#define IDS_NFO_OVPN_STATE_UNKNOWN              40193
